require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - ".git/**/*"
    - "bin/*"
    - "db/schema.rb"
  TargetRubyVersion: 2.7.3
  SuggestExtensions: false

Layout/LineLength:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 40
  IgnoredMethods: ["describe", "context", "register", register_page]
